# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build: #ToDo: rename to test, but require at least 1 build
    docker:
      # NOTE: Keep the image below in sync with what we use in the Dockerfile
      - image: circleci/node:8.9.1-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test-single

      # deployment
      #- deploy: 
      #    command: $DOCKER_HUB_TRIGGER

  deploy:
    docker: 
    - image: node:8.9.1-alpine
    #   auth:
    #   #Put the contents of keyfile.json into an environment variable for the build called GCR_CREDS, which is then passed in.
    #     username: _json_key
    #     password: $GOOGLE_AUTH

    steps:
      - run: 
          name: Dump Google Cloud Credentials to file
          command: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json

      - run:
          name: Install kubectl
          command: apk add --update ca-certificates \
                   && apk add --update -t deps curl \
                   && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/usr/local/bin/kubectl \
                   && chmod +x /usr/local/bin/kubectl \
                   && apk del --purge deps \
                   && rm /var/cache/apk/*

      - run: 
          name: Test kubectl commands
          command: kubectl --help

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master