apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: game-of-life
  namespace: default
  labels:
    app: game-of-life
spec:
  replicas: 1 # Number of pods we want
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: game-of-life
  template:
    metadata:
      labels:
        app: game-of-life
    spec:
      containers:
      - name: game-of-life
        image: jamesharrisonza/gameoflifetypescript
        ports:
        - containerPort: 42420